server:
  port: 8100

spring:
  application:
    name: fusion-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        group: FUSION_SERVICE_GROUP
        cluster-name: enhao-local
      config:
        server-addr: 127.0.0.1:8848
        group: FUSION_CONFIG_GROUP # 默认组，可以被 ${spring.config.import} 里?后group覆盖
        refresh-enabled: true # 是否开启动态刷新，默认开启，可以被 ${spring.config.import} 里?后refreshEnabled覆盖
      username: nacos
      password: nacos
    sentinel:
      enabled: true # 默认 true
      eager: true # 默认 false，是否在 Spring 容器启动时就初始化。默认在第一次调用时初始化
      http-method-specify: true # 默认 false，是否添加 http method 前缀
      web-context-unify: true # 默认为 true，流控模式如果是链路，需要配置成 false
      transport:
        port: 8719 # 启动一个 Http Server，该 Server 会与 Sentinel 控制台做交互。如果端口被占用，会自动+1，直到找到未被占用的端口
        dashboard: localhost:8080
        heartbeat-interval-ms: 5000 # 与控制台心跳间隔
      filter:
        enabled: false # 默认 true，网关设置为false
        url-patterns: # 拦截器拦截路径
          - '/**'
      log:
        dir: logs/csp/${spring.application.name}-${server.port}
      datasource: # 动态数据源，需对 sentinel-dashboard 做改造，详见 https://github.com/liangenhao/Sentinel/tree/master/sentinel-dashboard
        ds-gw-flow:
          nacos:
            username: ${spring.cloud.nacos.username}
            password: ${spring.cloud.nacos.password}
            server-addr: 127.0.0.1:8848
            group-id: SENTINEL_RULES_CONFIG_GROUP # 特别注意: 这里是 group-id，不是 group，和 spring.cloud.nacos.config 的配置 key 是不同的！
            data-type: json # 支持: json、xml、custom，当为 custom 时，指定 converter-class 配置项，写类全路径名
            rule-type: gw-flow
            data-id: ${spring.application.name}-gw-flow-rules
        ds-gw-api-group:
          nacos:
            username: ${spring.cloud.nacos.username}
            password: ${spring.cloud.nacos.password}
            server-addr: 127.0.0.1:8848
            group-id: SENTINEL_RULES_CONFIG_GROUP
            data-type: json
            rule-type: gw-api-group
            data-id: ${spring.application.name}-gw-api-group-rules
        ds-degrade:
          nacos:
            username: ${spring.cloud.nacos.username}
            password: ${spring.cloud.nacos.password}
            server-addr: 127.0.0.1:8848
            group-id: SENTINEL_RULES_CONFIG_GROUP
            data-type: json
            rule-type: degrade # 熔断规则
            data-id: ${spring.application.name}-degrade-rules
    gateway:
      httpclient:
        connect-timeout: 1000 # 全局连接超时时间
        response-timeout: 5s # 全局响应超时时间
      routes:
        - id: fusion-consumer
          uri: lb://fusion-consumer
          predicates:
            - Path=/consumer/**
          filters:
            - StripPrefix=1
          metadata:
            response-timeout: 200 # pre-route 超时时间，单位毫秒，覆盖全局配置，-1 表示禁用全局配置
            connect-timeout: 200
        - id: external-service
          uri: http://127.0.0.1:9000
          predicates:
            - Path=/external-api/**
          filters:
            - StripPrefix=1
  config:
    import:
      - optional:nacos:${spring.application.name}.yml?group=FUSION_CONFIG_GROUP&refreshEnabled=true
