server:
  port: 9000
spring:
  application:
    name: fusion-provider
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        group: FUSION_SERVICE_GROUP
        cluster-name: enhao-local
      config:
        server-addr: 127.0.0.1:8848
        group: FUSION_CONFIG_GROUP # 默认组，可以被 ${spring.config.import} 里?后group覆盖
        refresh-enabled: true # 是否开启动态刷新，默认开启，可以被 ${spring.config.import} 里?后refreshEnabled覆盖
      username: nacos
      password: nacos
    sentinel:
      eager: true # 默认 false，是否在 Spring 容器启动时就初始化。默认在第一次调用时初始化
      http-method-specify: true # 默认 false，是否添加 http method 前缀
      web-context-unify: true # 默认为 true，流控模式如果是链路，需要配置成 false
      transport:
        port: 8719 # 启动一个 Http Server，该 Server 会与 Sentinel 控制台做交互。如果端口被占用，会自动+1，直到找到未被占用的端口
        dashboard: localhost:8080
        heartbeat-interval-ms: 5000 # 与控制台心跳间隔
      filter:
        enabled: true # 默认 true，是否开启对 Spring webmvc 的拦截器
        url-patterns: # 拦截器拦截路径
          - '/**'
      log:
        dir: logs/${spring.application.name}
      datasource: # 动态数据源，需对 sentinel-dashboard 做改造，详见 https://github.com/liangenhao/Sentinel/tree/master/sentinel-dashboard
        ds-flow:
          nacos:
            username: ${spring.cloud.nacos.username}
            password: ${spring.cloud.nacos.password}
            server-addr: 127.0.0.1:8848
            group-id: SENTINEL_RULES_CONFIG_GROUP # 特别注意: 这里是 group-id，不是 group，和 spring.cloud.nacos.config 的配置 key 是不同的！
            data-type: json # 支持: json、xml、custom，当为 custom 时，指定 converter-class 配置项，写类全路径名
            rule-type: flow # 流控规则
            data-id: ${spring.application.name}-flow-rules
        ds-degrade:
          nacos:
            username: ${spring.cloud.nacos.username}
            password: ${spring.cloud.nacos.password}
            server-addr: 127.0.0.1:8848
            group-id: SENTINEL_RULES_CONFIG_GROUP
            data-type: json
            rule-type: degrade # 熔断规则
            data-id: ${spring.application.name}-degrade-rules
  config:
    # https://sca.aliyun.com/zh-cn/docs/2021.0.5.0/user-guide/nacos/advanced-guide#springcconfigimport-%E5%BC%95%E5%85%A5
    import:
      - optional:nacos:fusion-provider.yml?group=FUSION_CONFIG_GROUP&refreshEnabled=true
  profiles:
    active: dev # 当前激活的环境
# Spring Boot Actuator
# 所有的endpoints均暴露在/actuator下
management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: '*'

providerCustomKey: hello-config

fusion:
  env-key: default-provider
