server:
  port: 11000
spring:
  application:
    name: fusion-elasticsearch-java
logging:
  level:
    root: info
fusion:
  elasticsearch:
    username: xxx
    password: xxx
    ca-certificate-path: "xxx"
